version: '3.9'

services:
  geth:
    image: ethereum/client-go:v1.13.15
    container_name: geth
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - ../../../node1:/root/.ethereum
      - ../../../pwd.text:/root/pwd.text
    command: >
      --http
      --http.addr "0.0.0.0"
      --http.port 8545
      --http.corsdomain "*"
      --http.vhosts "*"
      --ws
      --ws.addr "0.0.0.0"
      --ws.port 8546
      --ws.origins "*"
      --http.api "eth,net,web3,personal,clique,admin,miner,debug,txpool"
      --allow-insecure-unlock
      --mine
      --miner.etherbase "0x91321c50FEE277c97eb3e0D333308b4f2C2ff824"
      --unlock "0x91321c50FEE277c97eb3e0D333308b4f2C2ff824"
      --password /root/pwd.text
      --ipcdisable
      --networkid 243522
      --verbosity 4 